'use strict';

// require modules
var autoprefixer 	= require('gulp-autoprefixer'),
	cleancss 		= require('gulp-clean-css'),
	header 			= require('gulp-header'),
	gulp 			= require('gulp'),
	rename 			= require('gulp-rename'),
	browserSync 	= require('browser-sync'),
	sass 			= require('gulp-sass'),
	sassGlob 		= require('gulp-sass-glob-import');

// browserSync var
var reload      = browserSync.reload;

// paths for browserSync
var src = {
    scss: 'sass/**/*.scss',
    html: '*.html'
};

var banner = {
	content :
	'/*!\n' +
	" * DON'T EDIT THIS FILE!\n" +
	' * Generated by Gulp in ' + new Date().getFullYear() + '\n' +
	' */\n\n'
};

/**
 *  Sass handling: compiling, autoprefix, banner, minify & output
 */
gulp.task('sass', function() {
	return gulp.src('./sass/*.scss')
		.pipe(sassGlob())
		.pipe(sass({errLogToConsole: true}))
		.pipe(autoprefixer({
			browsers: ['last 2 versions']
		}))
		.pipe(cleancss()) // minify
		.pipe(header(banner.content))
		.pipe(rename('style.min.css'))
		.pipe(gulp.dest('./'))
        .pipe(reload({stream: true}));
});

/**
 *  Browser sync
 */
gulp.task('serve', ['sass'], function() {

    browserSync({
        server: "./"
    });

    gulp.watch(src.scss, ['sass']);
    gulp.watch(src.html).on('change', reload);
});

/**
 * Build all and watch task at the beginning
 */
gulp.task('default', ['serve']);